### ISSUE TITLE
log message: LineRing not closed, is output on the wrong place

### ISSUE THREAD

**Issue by renato1987** [claeis/iox-ili#32]
Falls die RingLine nicht geschlossen wurde, wird die Konvertierung von iox nach jts wird aufgrund der
Klasse: jts.geom.LinearRing und dessen Methode: validateConstruction() und
Ausgabe: Points of LinearRing do not form a closed linestring, wird richtig durchgeführt.

Die Fehlermeldung soll zu späterer Zeit in der Klasse: ItfSurfaceLinetable2Polygon in der Meldung: invalid ring line... ausgegeben werden.

**Comment by claeis** [comment]
Bitte Unit-Test für LinearRing und CompoundCurveRing machen, der das (vermeintliche) Problem in validateConstruction() reproduziert.
